## ***Data Cleaning*** KNOW this

### Getting started with Pandas

- When importing packageds, pyton allows us to use custom names for the packages for brevity

In [1]:
import numpy as np
import pandas as pd

np.sin(np.pi/2)

np.float64(1.0)

In [2]:
from pandas import Series, DataFrame

- We will use 2 submodules of pandas called Series and DataFrame - two workhorse data structures

- from pandas import *
- do not use this as it is ALL of pandas
- pecifiy what you want to import from pandas

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj
obj.array
obj.index


# this is working with a series

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

### Data Series

A series is a one-dimensional set of values with an *index* attached to those values. 
A series is a one-dimension al array like ojbect containing a sequence of values of the *same type* and an associated array of **data labels**, called its *index*
and panda will always start the index in the column with a 0
so think 
### 0     4
### 1     7
### 2    -5

A series with an index identifying each data point with a lable is more useful
ex - the numbers 4, 6... now being "d",....
obj is just the variable name - can be anything - meaning replace the defaul 0,1,2 with your own useful info

In [5]:
obj2 = pd.Series ([4, 7, -5, 3], index = ["d", "b", "a", "c "])
obj2

d     4
b     7
a    -5
c     3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c '], dtype='str')

In [7]:
obj2["a"]

np.int64(-5)

you told pandas the the letters to assign(label) the `index`. obj2["a] is just telling pandas go get the data in the 'a' cell, which in our example case would be -5.

But `Series` is limited to single data set within one column. you just index it by attaching values to the data. we changed the default numberic index into lables when we did `index=["d"], "b"....`

### DataFrame
-  much more useful - DataFrame = the spreadsheet

A table of data containing an **ordered** and ***named*** collection of columns, each of which can be a different value type (numeric, strong, Boolean, etc.)

A DataFrame has both a row AND a column index. that is basically like excel spreadsheet living in python

In [8]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data) # this calls my new table 'frame' and says apply the funtion dataframe from pandas to the values I assigned above when i defined data

frame

frame.head()

frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

`frame.head()` looks at the first few rows

`frame["state"]` to retreive one column

In [9]:
frame["state"] # look at anything that is in my defined data frame in the column I called state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

notice how panda is telling me Name: state, dtype: str. its telling me pulling one column out of a DataFrame gives you a series

`frame["state"]` means get the item labled "state" from the dataFrame

In [10]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [11]:
frame.loc[1]

# use .loc[] to find particular row. filter with locaiton function

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [12]:
frame.describe()

# describe() gives you a statistical summary

              year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

### DataFrame - adding/removing data

In [13]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5]) # this is saying that the index is 2, 4, and 5 and the values are -1.2, -1.5, and -1.7
frame["debt"] = val # this is adding a new column to the frame called debt and the values are -1.2, -1.5, and -1.7

In [14]:
frame # if you don't provide the values for the other rows, they will be NaN (not a number) because they are missing values

    state  year  pop  debt
0    Ohio  2000  1.5   NaN
1    Ohio  2001  1.7   NaN
2    Ohio  2002  3.6  -1.2
3  Nevada  2001  2.4   NaN
4  Nevada  2002  2.9  -1.5
5  Nevada  2003  3.2  -1.7

In [15]:
del frame["debt"] # this is deleting the debt column from the frame from the original data content

In [16]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [17]:
frame.columns # This gives us the name of the columns in the frame. its a index series in this example

Index(['state', 'year', 'pop'], dtype='str')

### Essential Functions:

- Redindexing Series

In [18]:
obj=pd.Series([4.5, 7.2, -5.3, 3.6])
obj

0    4.5
1    7.2
2   -5.3
3    3.6
dtype: float64

In [19]:
obj2=obj.reindex(["a", "b", "c", "d", "e"]) # this is reindexing the series to have the index a, b, c, d, and e. the value for e will be NaN because it is not in the original series
obj2

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [20]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.arange(9).reshape((3,3)) # this is creating a 3x3 array with the values from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- Reindexing DataFRame

In [22]:
frame=pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas", "California"]) # this is creating a new data frame with 3 rows and 3 columns. the index is a, c, and d and the columns are Ohio, Texas, and California
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [23]:
frame2=frame.reindex(["a", "b", "c", "d"]) # this is reindexing the frame to have the index a, b, c, and d. the value for b will be NaN because it is not in the original frame
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [24]:
states=["Texas", "Utah", "California"] #ohio is missing therefore it is not included in the reindexing
frame.reindex(columns=states) # this is reindexing the frame to have the columns Texas, Utah, and California. the value for Utah will be NaN because it is not in the original frame

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Essential Functions: Selecting & Filtering Series

chanages the shape series or dataframe of what you have

In [25]:
obj = pd.Series(np.arange(4.0), index=["a", "b", "c", "d"]) #the decimal values are being created by using np.arange(4.0) which creates an array of 4 values starting from 0.0 to 3.0
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [26]:
obj["b"] # is accessing the value at index "b" which is 1.0

np.float64(1.0)

In [27]:
obj[1] # doesn't work because there is not idex with the label of 1

KeyError: 1

In [ ]:
obj[2:4] # is accessing the values at index 2 thru 4 but still doesn't work becuase our index is label with letters

c    2.0
d    3.0
dtype: float64

- `obj['b]` is the value at label b
- `obj[1]` second value using index 1 but doesn't work - the 1 is identified as an index label but we don't have one called 1
- `obj[2:4]` values at positions 2 and 3 - this works because we are telling pandas we are requesting a slice - panda will select by position. starts at position 2 and stops before position 4
- `obj[["b", "a", "d"]]` values at labels b,a and d in that order
- `obj[[1,3]]` values at position 1 and 3 won't work because it looks for index labels 1 and which don't exist
- `obj[obj<2]` Values less than 2

In [ ]:
obj[["b", "a", "d"]] # is accessing the values at index "b", "a", and "d" which are 1.0, 0.0, and 3.0

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj.loc[[1, 3]] # is accessing the values at index 1 and 3 which are 1.0 and 3.0

KeyError: "None of [Index([1, 3], dtype='int64')] are in the [index]"

In [ ]:
obj[obj < 2] # is accessing the values that are less than 2 which are -5.3 and 1.0

a    0.0
b    1.0
dtype: float64

in the square brackets is looking at it from a true or false perspective then the obj ?

### Essential Function: Selecting and Filtering DataFrame

In [ ]:
obj = pd.DataFrame(np.arange(9). reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas", "California"]) # this is creating a new data frame with 3 rows and 3 columns. the index is a, c, and d and the columns are Ohio, Texas, and California
obj

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"]) # this is creating a new data frame with 4 rows and 4 columns. the index is Ohio, Colorado, Utah, and New York and the columns are one, two, three, and four
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data["two"] # is accessing the column "two" which is a series with the values 1, 5, 9, and 13
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data[["three", "one"]] # is accessing the columns "three" and "one" which are a data frame with the values 2, 6, 10, and 14 for three and 0, 4, 8, and 12 for one
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data["two"] # is accessing the column "two" which is a series with the values 1, 5, 9, and 13
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data[data["three"] > 5] # is accessing the rows where the value in the column "three" is greater than 5 which are the rows with the index "Utah" and "New York"

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc["Colorado"] # is accessing the row with the index "Colorado" which is a series with the values 4, 5, 6, and 7 for the columns one, two, three, and four

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [ ]:
data.loc[["Colorado", "New York"]] # is accessing the rows with the index "Colorado" and "New York" which are a data frame with the values 4, 5, 6, and 7 for Colorado and 12, 13, 14, and 15 for New York for the columns one, two, three, and four

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [ ]:
data.loc[["Colorado", "Utah"], ["two", "three"]] # is accessing the rows with the index "Colorado" and "Utah" and the columns "two" and "three" which are a data frame with the values 5, 6, 9, and 10 for two and three

          two  three
Colorado    5      6
Utah        9     10

### Essential Functions: Sorting

To sort lexicographically (by row or column label), we can use the `sort_index` method,
which returns a new, sorted object.

In [ ]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"]) # this is creating a new series with the values 0, 1, 2, and 3 and the index is d, a, b, and c  
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int64>

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"]) # this is creating a new data frame with 2 rows and 4 columns. the index is three and one and the columns are d, a, b, and c

In [ ]:
frame.sort_index(axis="columns") # this is sorting the columns of the frame in ascending order

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

- but can be done in descending order too

In [ ]:
frame.sort_index(axis="columns", ascending=False)

   Texas  Ohio  California
a      1     0           2
c      4     3           5
d      7     6           8

In [ ]:
frame.sort_index(axis="columns").sort_index() # this isn't the most effective way to sort the frame but it is sorting the columns first and then sorting the rows. it is better to use sort_index(axis="columns", inplace=True) and then sort_index(inplace=True) to sort the frame in place

       a  b  c  d
one    5  6  7  4
three  1  2  3  0

- sort by value

In [ ]:
obj=pd.Series((4, 7, -3,2))

In [ ]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

- you can sort missing values to the start instead by using the `na_position` option

In [ ]:
obj.sort_values(na_position="first") # this is sorting the values of the series in ascending order and putting the NaN values first

2   -3
3    2
0    4
1    7
dtype: int64

- when sorting a dataframe, you can use the data in one or more columns as the sort keys

In [ ]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]}) # this is creating a new data frame with 4 rows and 2 columns. the index is 0, 1, 2, and 3 and the columns are b and a
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [ ]:
frame.sort_values("b") # this is sorting the frame by the values in the column "b" in ascending order

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [ ]:
frame.sort_values(["a", "b"]) # this is sorting the frame by the values in the column "a" first and then by the values in the column "b" in ascending order

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

- `pandas` objects include a set of common mathmatical and statistical methods

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"]) # this is creating a new data frame with 4 rows and 2 columns. the index is a, b, c, and d and the columns are one and two

In [ ]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

- There are also other helpful functions such as `count`, `describe`, `min`....

In [ ]:
import pandas as pd

In [ ]:
sdflights2022 = pd.read_csv("../data/sdflights2022.csv")
sdflights2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 86030 entries, 0 to 86029
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            86030 non-null  int64
 1   month           86030 non-null  int64
 2   day             86030 non-null  int64
 3   dep_time        84333 non-null  float64
 4   sched_dep_time  86030 non-null  int64
 5   dep_delay       84332 non-null  float64
 6   arr_time        84293 non-null  float64
 7   sched_arr_time  86030 non-null  int64
 8   arr_delay       84068 non-null  float64
 9   carrier         86030 non-null  str
 10  flight          86030 non-null  int64
 11  tailnum         85686 non-null  str
 12  origin          86030 non-null  str
 13  dest            86030 non-null  str
 14  air_time        84068 non-null  float64
 15  distance        86030 non-null  int64
 16  hour            86030 non-null  int64
 17  minute          86030 non-null  int64
 18  time_hour       86030 non-null  str
dtypes: float64(5), int64(9), str(5)
memory usage: 12.5 MB

In [ ]:
# sdflights2022[sdflights2022["air_time"]>60] # this is only for one condition which was airtime less than 60 minutes. you can add more conditions by using the & operator and adding more conditions in parentheses. for example, sdflights2022[(sdflights2022["air_time"]>60) & (sdflights2022["distance"]>1000)] would give you all flights that have an airtime greater than 60 minutes and a distance greater than 1000 miles.
sdflights2022[(sdflights2022["carrier"]=="DL") & (sdflights2022["carrier"]=="AA")]

Empty DataFrame
Columns: [year, month, day, dep_time, sched_dep_time, dep_delay, arr_time, sched_arr_time, arr_delay, carrier, flight, tailnum, origin, dest, air_time, distance, hour, minute, time_hour]
Index: []

In [ ]:
sdflights2022[(sdflights2022["arr_delay"] > 0) & (sdflights2022["dep_delay"]<0)] # this is filtering the data frame to only include rows where the arrival delay is greater than 0 and the departure delay is less than 0. this would give you all flights that arrived late but departed early.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2022,1,1,611.0,615,-4.0,943.0,922,21.0,DL,344,N871DN,SAN,SLC,99.0,626,6,15,2022-01-01T06:00:00Z
41,2022,1,1,824.0,825,-1.0,1149.0,1140,9.0,WN,479,N453WN,SAN,BOI,113.0,749,8,25,2022-01-01T08:00:00Z
54,2022,1,1,954.0,1000,-6.0,1443.0,1425,18.0,AS,94,N514AS,SAN,LIH,333.0,2676,10,0,2022-01-01T10:00:00Z
70,2022,1,1,1129.0,1130,-1.0,1501.0,1448,13.0,OO,490,N186SY,SAN,HDN,131.0,769,11,30,2022-01-01T11:00:00Z
79,2022,1,1,1232.0,1237,-5.0,1739.0,1736,3.0,AA,252,N567UW,SAN,DFW,137.0,1171,12,37,2022-01-01T12:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85913,2022,12,31,907.0,910,-3.0,1050.0,1045,5.0,WN,207,N8802Q,SAN,SMF,72.0,480,9,10,2022-12-31T09:00:00Z
85926,2022,12,31,1020.0,1025,-5.0,1154.0,1148,6.0,OO,402,N181SY,SAN,FAT,64.0,314,10,25,2022-12-31T10:00:00Z
85951,2022,12,31,1201.0,1205,-4.0,1354.0,1344,10.0,OO,379,N193SY,SAN,SFO,91.0,447,12,5,2022-12-31T12:00:00Z
85989,2022,12,31,1554.0,1555,-1.0,1716.0,1703,13.0,OO,395,N187SY,SAN,SBP,55.0,263,15,55,2022-12-31T15:00:00Z
86022,2022,12,31,2205.0,2208,-3.0,2351.0,2344,7.0,AS,26,N275AK,SAN,SFO,71.0,447,22,8,2022-12-31T22:00:00Z

In [ ]:
sdflights2022.sort_values("dep_delay").head(1) # this is sorting the data frame by the departure delay in ascending order. you can also use the ascending=False parameter to sort in descending order. for example, sdflights2022.sort_values(dep_delay, ascending=False) would sort the data frame by the departure delay in descending order.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
3582,2022,1,20,2150.0,2215,-25.0,513.0,534,-21.0,DL,131,N352DN,SAN,DTW,238.0,1956,22,15,2022-01-20T22:00:00Z

In [ ]:
sdflights2022.sort_values("dep_delay", ascending=False).head(1) # this is sorting the data frame by the departure delay in descending order and then by the arrival delay in ascending order. you can also use the ascending=[False, True] parameter to sort in descending order for the first column and ascending order for the second column. for example, sdflights2022.sort_values(by=["dep_delay", "arr_delay"], ascending=[False, True]) would sort the data frame by the departure delay in descending order and then by the arrival delay in ascending order.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
48649,2022,8,6,947.0,625,1642.0,1107.0,751,1636.0,AA,72,N125AA,SAN,PHX,53.0,304,6,25,2022-08-06T06:00:00Z

In [ ]:
sdflights2022["total_delay"] = sdflights2022["arr_delay"] + sdflights2022["dep_delay"] # this is creating a new column in the data frame called total_delay which is the sum of the arrival delay and the departure delay
sdflights2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 86030 entries, 0 to 86029
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            86030 non-null  int64
 1   month           86030 non-null  int64
 2   day             86030 non-null  int64
 3   dep_time        84333 non-null  float64
 4   sched_dep_time  86030 non-null  int64
 5   dep_delay       84332 non-null  float64
 6   arr_time        84293 non-null  float64
 7   sched_arr_time  86030 non-null  int64
 8   arr_delay       84068 non-null  float64
 9   carrier         86030 non-null  str
 10  flight          86030 non-null  int64
 11  tailnum         85686 non-null  str
 12  origin          86030 non-null  str
 13  dest            86030 non-null  str
 14  air_time        84068 non-null  float64
 15  distance        86030 non-null  int64
 16  hour            86030 non-null  int64
 17  minute          86030 non-null  int64
 18  time_hour       86030 non-null  str
 19  total_delay     84068 non-null  float64
dtypes: float64(6), int64(9), str(5)
memory usage: 13.1 MB

In [ ]:
sdflights22.sort_values("total_delay", ascenting=False).head(1) # this is sorting the data frame by the total delay in descending order and then returning the first row which is the flight with the longest total delay

NameError: name 'sdflights22' is not defined

### Handling Missing Data for Series
one of the simplest forms of cleaning data is filtering and filling NA values

In [ ]:
float_data=pd.Series([1.2, -3.5, np.nan, 0]) # this is creating a new series with the values 1.2, -3.5, NaN, and 0

In [ ]:
float_data.isna() # this is checking for missing values in the series

0    False
1    False
2     True
3    False
dtype: bool

- Some basic approaches for dealing with NA values include dropping them altogether, filling them with default values, or using interpolation

- when is ok to fill NA values with zero wuld be like test scores where the score is totally missing you can assume the score is a 0

In [ ]:
data=pd.Series([1, np.nan, 3.5, np.nan, 7]) # this is creating a new series with the values 1, NaN, 3.5, NaN, and 7
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.dropna() # this is dropping the missing values from the series and returning a new series with the values 1, 3.5, and 7

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data.dropna(how="all") #

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
data.dropna(axis="columns", how="all") # no axis named colums for object type Series

ValueError: No axis named columns for object type Series

- `pandas` also accomodates rules with certain number of allowable missing values

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"])
df.dropna(thresh=2) #thresh requires at least 2 nonmissing values in each row to keep it.

    one  two
b  7.10 -4.5
d  0.75 -1.3

In [ ]:
df.fillna({1: 0.5, 2: 0}) # this isn't working because my df columns are not 1 and 2

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
df.fillna({"one": 0.5, "two": 0})

    one  two
a  1.40  0.0
b  7.10 -4.5
c  0.50  0.0
d  0.75 -1.3

In [ ]:
data[data.notna()] # this is returning a new series with the values 1, 3.5, and 7 by using the notna() method to filter out the missing values

0    1.0
2    3.5
4    7.0
dtype: float64

- We can also fill `na` values with default values, with options to assingn different values per column

In [ ]:
data.fillna(0) # this is filling the missing values in the series with 0 and returning a new series with the values 1, 0, 3.5, 0, and 7

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"])

df.fillna(0)

    one  two
a  1.40  0.0
b  7.10 -4.5
c  0.00  0.0
d  0.75 -1.3

In [ ]:
data.ffill() # this is filling the missing values in the series with the last valid value and returning a new series with the values 1, 1, 3.5, 3.5, and 7

0    1.0
1    1.0
2    3.5
3    3.5
4    7.0
dtype: float64

In [ ]:
data.bfill() # this is filling the missing values in the series with the next valid value and returning a new series with the values 1, 3.5, 3.5, 7, and 7

0    1.0
1    3.5
2    3.5
3    7.0
4    7.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1., 6.5], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]]) # this is creating a new data frame with 4 rows and 3 columns. the index is 0, 1, 2, and 3 and the columns are 0, 1, and 2. the values are 1.0, 6.5, NaN, NaN, NaN, NaN, NaN, 6.5, and 3.0
data

     0    1    2
0  1.0  6.5  NaN
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

threshold works on values

### Data Cleaning: Removing Duplicats

- Using the fuction `duplicated` and `drop_duplicates`, we can find and handle duplicated rows

In [ ]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1,1,2,3,3,4,4]})
print(data)

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated() # what?

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

- By default, both methods consider all columns. Alternateivly, we can sepcify any subset of columnss to detect or drop duplicates

In [ ]:
data.drop_duplicates(subset=["k1"])

    k1  k2
0  one   1
1  two   1

- both methods also keep the first observed value combination by default. Passing `keep="last"` will return the last one from list

In [ ]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

### Data Cleaning: Replacing Values

- `replace` provides a *simpler and flexibly way to modify a subset of vlaues in an object

In [ ]:
data=pd.Series([1., -999., -1000., 3.])
print(data)
data

0       1.0
1    -999.0
2   -1000.0
3       3.0
dtype: float64

0       1.0
1    -999.0
2   -1000.0
3       3.0
dtype: float64

In [ ]:
data=pd.Series([1., -999., -1000., 3.])

data.replace(-999, np.nan)

0       1.0
1       NaN
2   -1000.0
3       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    NaN
3    3.0
dtype: float64

- you can also provide a dictionary

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    0.0
3    3.0
dtype: float64

- However, a more general approach is to use the function `map`

In [ ]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"],
                     "ounces": [4,3,12,6,7.5,8,3,5,6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
    "bacon": "pig", "pulled pork": "pig", "pastrami": "cow", "corned beef": "cow", "honey ham": "pig", "nova lox": "salmon"}

data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### End for quiz 1

### Data Cleaning: Detecting and filtering outliers

Consider a DataFrame with some normally distrubuted data.

- look into standard deviations

In [ ]:
import pandas as pd
import numpy as np
data = pd.DataFrame(np.random.standard_normal ((1000,4))) 
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017937    -0.059017    -0.028362     0.054958
std       1.000215     0.979042     0.991532     1.014099
min      -2.921373    -3.012993    -3.741807    -3.564981
25%      -0.690056    -0.711965    -0.670655    -0.628668
50%       0.004494    -0.056957     0.002233     0.059615
75%       0.694658     0.606039     0.613102     0.743072
max       3.059636     2.629831     3.029733     3.419804

Suppose we wanted to find values in one column excedding 3 standard deviations (absolute)

In [ ]:
col=data[2] # from the data frame named data, select column 2 and assing it to the variable `col`
# selects the column labeled 2 (3rd one) - the result is a series - not a dataframe

col[col.abs() > 3] # show me the condition of whatever i put in [] - true or false for the absolute value fuction
# show me the original values in column 2 whose absolute values are greater than 3
# .abs() takes the absolute value of each number
# >3 checks whether that abs value exceedes3 which will result in true or false boolean vlaues table
# the outer col[] means select values from the original series
# the innter col.abs()>3 means but only select the positions where this condition is true

98     3.022190
142    3.513043
394    3.688976
457    3.070244
Name: 2, dtype: float64

- the above are technically outliers of the 3 which is the normal range

- to select all rows haveing a value exceeding 3 or -3, you can use the any methond on a Boolean DataFrame

In [ ]:
data[(data.abs() >3).any(axis='columns')]

            0         1         2         3
52  -0.423070  3.161988 -0.860334 -1.135130
98  -0.469814  0.701400  3.022190  0.389123
142  0.777203  0.137418  3.513043 -0.651838
242 -0.086225 -3.185055 -0.711651 -1.936200
248  1.185734  3.326186 -1.380161  0.861751
293  0.803710 -0.644193  0.870826 -3.258874
352 -0.593971 -3.013623 -0.155416  0.614044
354  2.289435  0.589249 -1.103476  3.320697
361  0.235184  5.013641 -1.052080  0.112732
394  0.395989 -1.203884  3.688976  0.699111
457 -0.371246 -0.307189  3.070244 -0.120373
581 -0.022366 -3.151017 -0.400303  0.580940
637  0.579207  1.301429 -0.421580 -3.251254
725 -0.659792  1.121417 -0.281243  3.241250
733 -0.997264 -3.032887 -0.619305  0.159526
894  3.258240 -0.983876  0.267549 -1.197467
911  3.093701  1.348720 -0.554869 -0.288447
927 -3.429693 -2.039712  0.035237  0.945800
951  3.067257  0.596936 -1.412810 -0.338840

### Often, when working with uncleaned data, individual data types may not be in the desired format.

In [ ]:
val=pd.Series(['20250101','20250301','20250401','20250501'])
val

0    20250101
1    20250301
2    20250401
3    20250501
dtype: str

- `pandas to_datetime` function converts a scalar, array-like, Series, or DataFrame to a pandas `datetime` object

In [ ]:
pd.to_datetime(val)

0   2025-01-01
1   2025-03-01
2   2025-04-01
3   2025-05-01
dtype: datetime64[us]

- for date conversions, in particular, a `format` option can be used to handle various conventions

In [ ]:
val=pd.Series(['Jan2025','Feb2025','Mar2025','Apr2025'])

pd.to_datetime(val, format='%b%Y')

0   2025-01-01
1   2025-02-01
2   2025-03-01
3   2025-04-01
dtype: datetime64[us]

- This format type is called a **directive**

Practice sdflights22 is active participatioon so the Let's practice - for 10/19

In [29]:
sdflights2022 = pd.read_csv("../data/sdflights2022.csv")

In [ ]:
df = pd.read_csv("../data/sdflights2022.csv")

df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2022,1,1,611.0,615,-4.0,943.0,922,21.0,DL,344,N871DN,SAN,SLC,99.0,626,6,15,2022-01-01T06:00:00Z
1,2022,1,1,612.0,618,-6.0,713.0,715,-2.0,OO,526,N285SY,SAN,LAX,31.0,109,6,18,2022-01-01T06:00:00Z
2,2022,1,1,612.0,615,-3.0,1306.0,1327,-21.0,DL,95,N1604R,SAN,ATL,207.0,1892,6,15,2022-01-01T06:00:00Z
3,2022,1,1,612.0,615,-3.0,1141.0,1156,-15.0,DL,113,N352DN,SAN,MSP,182.0,1532,6,15,2022-01-01T06:00:00Z
4,2022,1,1,612.0,615,-3.0,921.0,925,-4.0,AS,23,N273AK,SAN,SEA,156.0,1050,6,15,2022-01-01T06:00:00Z

In [ ]:
# df.isna()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86025,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86026,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86027,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False
86028,False,False,False,True,False,True,True,False,True,False,False,False,False,False,True,False,False,False,False
86029,False,False,False,True,False,True,True,False,True,False,False,False,False,False,True,False,False,False,False

In [30]:
sdflights2022.isna().sum()

year                 0
month                0
day                  0
dep_time          1697
sched_dep_time       0
dep_delay         1698
arr_time          1737
sched_arr_time       0
arr_delay         1962
carrier              0
flight               0
tailnum            344
origin               0
dest                 0
air_time          1962
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [ ]:
df.isna().sum(axis="index")

year                 0
month                0
day                  0
dep_time          1697
sched_dep_time       0
dep_delay         1698
arr_time          1737
sched_arr_time       0
arr_delay         1962
carrier              0
flight               0
tailnum            344
origin               0
dest                 0
air_time          1962
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

- the best way to handle NA values are based on the data itself. If makes sense for the data set can drop all together fill with default value or use interpolation. But say you were using data set for grades and someone neeed that has na values you wouldn't just want to drop them alltogether nor replace it with a defaul value.

In [ ]:
df["arr_delay"].describe()

count    84068.000000
mean         4.894050
std         47.712944
min        -86.000000
25%        -13.000000
50%         -5.000000
75%          9.000000
max       1636.000000
Name: arr_delay, dtype: float64

- should have replaced the NA values before we did the calbulation
- something quantative - once remove NA - it goes away - it really can change based on your data
- replace orver remove? - can afffect the context

- should not assume the vaue is 0 because it can change the mean result

In [ ]:
col=df["arr_delay"]

df[(col - col.mean()).abs()>=3*col.std()]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
91,2022,1,1,1318.0,1010,188.0,1707.0,1415,172.0,AS,27,N431AS,SAN,KOA,329.0,2556,10,10,2022-01-01T10:00:00Z
167,2022,1,2,118.0,2145,213.0,912.0,544,208.0,B6,130,N605JB,SAN,EWR,271.0,2425,21,45,2022-01-02T21:00:00Z
272,2022,1,2,1354.0,1021,213.0,1846.0,1529,197.0,UA,179,N37252,SAN,IAH,147.0,1303,10,21,2022-01-02T10:00:00Z
288,2022,1,2,1525.0,625,540.0,1920.0,953,567.0,UA,255,N879UA,SAN,DEN,114.0,853,6,25,2022-01-02T06:00:00Z
460,2022,1,3,1239.0,950,169.0,1546.0,1256,170.0,OO,438,N173SY,SAN,SLC,92.0,626,9,50,2022-01-03T09:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85708,2022,12,30,1215.0,930,165.0,1408.0,1110,178.0,OO,371,N410SY,SAN,SFO,85.0,447,9,30,2022-12-30T09:00:00Z
85779,2022,12,30,1703.0,1430,153.0,1844.0,1609,155.0,OO,401,N171SY,SAN,SFO,76.0,447,14,30,2022-12-30T14:00:00Z
85851,2022,12,30,2325.0,2025,180.0,216.0,2310,186.0,G4,443,276NV,SAN,PVU,89.0,599,20,25,2022-12-30T20:00:00Z
86006,2022,12,31,1842.0,1415,267.0,2021.0,1551,270.0,OO,387,N400SY,SAN,SJC,67.0,417,14,15,2022-12-31T14:00:00Z
86011,2022,12,31,1917.0,1555,202.0,2119.0,1810,189.0,WN,16,N934WN,SAN,PHX,45.0,304,15,55,2022-12-31T15:00:00Z

- the standard way of saying outlier is with the 3 standard devisiations below or above assuming its normally distruted

In [31]:
arr_delay_std=sdflights2022["arr_delay"].std()
arr_delay_std

np.float64(47.71294375253487)

In [ ]:
col=df["arr_delay"]

((col - col.mean()).abs()>=3*col.std()).sum()

np.int64(941)